/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.ballerina.persist.dataservice;

import io.ballerina.compiler.syntax.tree.SyntaxTree;
import io.ballerina.persist.BalException;
import io.ballerina.persist.dataservice.DataServiceOptions.Operation;
import io.ballerina.persist.models.Entity;
import io.ballerina.persist.models.EntityField;
import io.ballerina.tools.text.TextDocuments;
import org.ballerinalang.formatter.core.Formatter;
import org.ballerinalang.formatter.core.FormatterException;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import static io.ballerina.persist.nodegenerator.syntax.constants.BalSyntaxConstants.AUTOGENERATED_FILE_COMMENT;
import static io.ballerina.persist.nodegenerator.syntax.constants.BalSyntaxConstants.AUTO_GENERATED_COMMENT;
import static io.ballerina.persist.nodegenerator.syntax.constants.BalSyntaxConstants.COMMENT_SHOULD_NOT_BE_MODIFIED;

/**
 * Generates the sources of an HTTP data service.
 */
public class HttpDataServiceGenerator {

    public static final String SERVICE_FILE = "persist_dataservice.bal";
    public static final String CONFIG_FILE = "persist_dataservice_config.bal";

    private static final String NEW_LINE = System.lineSeparator();
    private static final String STRING_TYPE = "string";

    private final DataServiceModel model;

    public HttpDataServiceGenerator(DataServiceModel model) {
        this.model = model;
    }

    /**
     * Generates the file holding the listener, the service and its types.
     *
     * @return the formatted source of the service file
     * @throws BalException if the source cannot be formatted
     */
    public String generateService() throws BalException {
        StringBuilder source = header();
        source.append("import ballerina/dataservice;").append(NEW_LINE)
                .append("import ballerina/http;").append(NEW_LINE)
                .append("import ballerina/log;").append(NEW_LINE)
                .append("import ballerina/persist;").append(NEW_LINE);
        if (needsPathEncoding()) {
            source.append("import ballerina/url;").append(NEW_LINE);
        }
        source.append(NEW_LINE)
                .append("final Client dataserviceClient = check new ();").append(NEW_LINE).append(NEW_LINE)
                .append("listener http:Listener dataserviceListener = new (dataservicePort, ")
                .append("dataserviceListenerConfig);").append(NEW_LINE).append(NEW_LINE)
                .append("service ").append(servicePath()).append(" on dataserviceListener {").append(NEW_LINE);
        for (ExposedEntity exposed : model.entities()) {
            appendResources(source, exposed);
        }
        source.append("}").append(NEW_LINE);
        for (ExposedEntity exposed : model.entities()) {
            appendEntityTypes(source, exposed);
        }
        appendErrorTypes(source);
        appendErrorFunctions(source);
        if (needsPathEncoding()) {
            appendPathEncodingFunction(source);
        }
        return format(source.toString());
    }

    /**
     * Generates the file holding the configurable listener settings.
     *
     * @return the formatted source of the configuration file
     * @throws BalException if the source cannot be formatted
     */
    public String generateConfig() throws BalException {
        StringBuilder source = header();
        source.append("import ballerina/http;").append(NEW_LINE).append(NEW_LINE)
                .append("configurable int dataservicePort = 9090;").append(NEW_LINE)
                .append("configurable http:ListenerConfiguration dataserviceListenerConfig = {};").append(NEW_LINE);
        return format(source.toString());
    }

    private void appendResources(StringBuilder source, ExposedEntity exposed) {
        Entity entity = exposed.entity();
        Map<String, String> values = Map.of(
                "Entity", entity.getEntityName(),
                "resource", entity.getClientResourceName(),
                "keyParams", keyPathParams(entity),
                "clientKeyPath", clientKeyPath(entity),
                "keyText", keyText(entity),
                "keyType", keyType(entity),
                "keyBinding", keyBinding(entity),
                "location", location(entity));

        if (exposed.allows(Operation.READ)) {
            source.append(fill("""

                resource function get @resource@() returns @Entity@List|DataserviceInternalError {
                    @Entity@[]|persist:Error items = from @Entity@ item in dataserviceClient->/@resource@(@Entity@)
                        select item;
                    if items is persist:Error {
                        return dataserviceInternalError(items);
                    }
                    return {items};
                }

                resource function get @resource@@keyParams@() returns @Entity@|DataserviceErrorResponse {
                    @Entity@|persist:Error item = dataserviceClient->/@resource@@clientKeyPath@;
                    if item is persist:Error {
                        return dataserviceErrorResponse(item, "@Entity@", @keyText@);
                    }
                    return item;
                }
            """, values));
        }
        if (exposed.allows(Operation.CREATE)) {
            source.append(fill("""

                resource function post @resource@(@Entity@Insert|@Entity@Insert[] payload)
                        returns @Entity@Created|@Entity@ListCreated|DataserviceErrorResponse {
                    @Entity@Insert[] values = payload is @Entity@Insert[] ? payload : [payload];
                    @keyType@[]|persist:Error keys = dataserviceClient->/@resource@.post(values);
                    if keys is persist:Error {
                        return dataserviceErrorResponse(keys, "@Entity@");
                    }
                    @Entity@[] items = [];
                    foreach @keyBinding@ in keys {
                        @Entity@|persist:Error item = dataserviceClient->/@resource@@clientKeyPath@;
                        if item is persist:Error {
                            return dataserviceErrorResponse(item, "@Entity@", @keyText@);
                        }
                        items.push(item);
                    }
                    if payload is @Entity@Insert[] {
                        return {body: {items}};
                    }
                    @keyBinding@ = keys[0];
                    return {headers: {"Location": @location@}, body: items[0]};
                }
            """, values));
        }
        if (exposed.allows(Operation.UPDATE)) {
            source.append(fill("""

                resource function patch @resource@@keyParams@(@Entity@Update payload)
                        returns @Entity@|DataserviceErrorResponse {
                    @Entity@|persist:Error item = dataserviceClient->/@resource@@clientKeyPath@.put(payload);
                    if item is persist:Error {
                        return dataserviceErrorResponse(item, "@Entity@", @keyText@);
                    }
                    return item;
                }
            """, values));
        }
        if (exposed.allows(Operation.DELETE)) {
            source.append(fill("""

                resource function delete @resource@@keyParams@() returns @Entity@|DataserviceErrorResponse {
                    @Entity@|persist:Error item = dataserviceClient->/@resource@@clientKeyPath@.delete();
                    if item is persist:Error {
                        return dataserviceErrorResponse(item, "@Entity@", @keyText@);
                    }
                    return item;
                }
            """, values));
        }
    }

    private void appendEntityTypes(StringBuilder source, ExposedEntity exposed) {
        String name = exposed.entity().getEntityName();
        if (exposed.allows(Operation.READ) || exposed.allows(Operation.CREATE)) {
            source.append(fill("""

                    # A list of `@Entity@` records.
                    #
                    # + items - The records
                    public type @Entity@List record {|
                        @Entity@[] items;
                    |};
                    """, Map.of("Entity", name)));
        }
        if (exposed.allows(Operation.CREATE)) {
            source.append(fill("""

                    # The response for a created `@Entity@` record.
                    #
                    # + body - The created record
                    public type @Entity@Created record {|
                        *http:Created;
                        @Entity@ body;
                    |};

                    # The response for created `@Entity@` records.
                    #
                    # + body - The created records
                    public type @Entity@ListCreated record {|
                        *http:Created;
                        @Entity@List body;
                    |};
                    """, Map.of("Entity", name)));
        }
    }

    private static void appendErrorTypes(StringBuilder source) {
        source.append("""

                # The response when no record has the given key.
                #
                # + body - The error
                public type DataserviceNotFound record {|
                    *http:NotFound;
                    dataservice:DataserviceError body;
                |};

                # The response when a record with the key or a unique value already exists.
                #
                # + body - The error
                public type DataserviceConflict record {|
                    *http:Conflict;
                    dataservice:DataserviceError body;
                |};

                # The response when a write violates a constraint.
                #
                # + body - The error
                public type DataserviceConstraintViolation record {|
                    *http:Conflict;
                    dataservice:DataserviceError body;
                |};

                # The response for any other failure.
                #
                # + body - The error
                public type DataserviceInternalError record {|
                    *http:InternalServerError;
                    dataservice:DataserviceError body;
                |};

                # An error response of a data service operation.
                public type DataserviceErrorResponse DataserviceNotFound|DataserviceConflict
                    |DataserviceConstraintViolation|DataserviceInternalError;
                """);
    }

    private static void appendErrorFunctions(StringBuilder source) {
        source.append("""

                function dataserviceErrorResponse(persist:Error err, string entity, string key = "")
                        returns DataserviceErrorResponse {
                    if err is persist:NotFoundError {
                        return <DataserviceNotFound>{
                            body: {
                                code: dataservice:NOT_FOUND,
                                message: string `A record with the key '${key}' does not exist for the entity \
                '${entity}'.`
                            }
                        };
                    }
                    if err is persist:AlreadyExistsError {
                        return <DataserviceConflict>{
                            body: {
                                code: dataservice:CONFLICT,
                                message: string `A record that conflicts with an existing record of the entity \
                '${entity}' already exists.`
                            }
                        };
                    }
                    if err is persist:ConstraintViolationError {
                        log:printError(string `Constraint violation on the entity '${entity}'.`, err);
                        return <DataserviceConstraintViolation>{
                            body: {
                                code: dataservice:CONSTRAINT_VIOLATION,
                                message: string `The operation violates a constraint of the entity '${entity}'.`
                            }
                        };
                    }
                    return dataserviceInternalError(err);
                }

                function dataserviceInternalError(persist:Error err) returns DataserviceInternalError {
                    log:printError("Data service operation failed.", err);
                    return {body: {code: dataservice:INTERNAL, message: "An internal error occurred."}};
                }
                """);
    }

    // `url:encode` uses form encoding, which writes a space as '+'; a path segment needs '%20'.
    private static void appendPathEncodingFunction(StringBuilder source) {
        source.append("""

                function dataserviceEncodePathSegment(string value) returns string {
                    string|url:Error encoded = url:encode(value, "UTF-8");
                    return encoded is string ? re `\\+`.replaceAll(encoded, "%20") : value;
                }
                """);
    }

    private static String fill(String template, Map<String, String> values) {
        String filled = template;
        for (Map.Entry<String, String> value : values.entrySet()) {
            filled = filled.replace("@" + value.getKey() + "@", value.getValue());
        }
        return filled;
    }

    private boolean needsPathEncoding() {
        return model.entities().stream().anyMatch(exposed -> exposed.allows(Operation.CREATE)
                && exposed.entity().getKeys().stream().anyMatch(key -> STRING_TYPE.equals(key.getFieldType())));
    }

    // A base path segment that is not an identifier is written with its non-identifier characters escaped.
    private String servicePath() {
        String basePath = model.options().basePath();
        if (basePath.isEmpty()) {
            return "/";
        }
        StringBuilder path = new StringBuilder();
        for (String segment : basePath.substring(1).split("/")) {
            path.append('/');
            for (int i = 0; i < segment.length(); i++) {
                char c = segment.charAt(i);
                boolean identifierChar = Character.isLetter(c) || c == '_' || (i > 0 && Character.isDigit(c));
                if (!identifierChar) {
                    path.append('\\');
                }
                path.append(c);
            }
        }
        return path.toString();
    }

    private static String keyPathParams(Entity entity) {
        return entity.getKeys().stream()
                .map(key -> String.format("/[%s %s]", key.getFieldType(), key.getFieldName()))
                .collect(Collectors.joining());
    }

    private static String clientKeyPath(Entity entity) {
        return entity.getKeys().stream()
                .map(key -> String.format("/[%s]", key.getFieldName()))
                .collect(Collectors.joining());
    }

    private static String keyText(Entity entity) {
        return entity.getKeys().stream()
                .map(key -> "${" + key.getFieldName() + "}")
                .collect(Collectors.joining("/", "string `", "`"));
    }

    private static String keyType(Entity entity) {
        List<EntityField> keys = entity.getKeys();
        if (keys.size() == 1) {
            return keys.get(0).getFieldType();
        }
        return keys.stream().map(EntityField::getFieldType).collect(Collectors.joining(", ", "[", "]"));
    }

    private static String keyBinding(Entity entity) {
        List<EntityField> keys = entity.getKeys();
        if (keys.size() == 1) {
            return keys.get(0).getFieldType() + " " + keys.get(0).getFieldName();
        }
        return keyType(entity) + " " + keys.stream().map(EntityField::getFieldName)
                .collect(Collectors.joining(", ", "[", "]"));
    }

    private String location(Entity entity) {
        StringBuilder location = new StringBuilder("string `")
                .append(model.options().basePath()).append('/').append(entity.getClientResourceName());
        for (EntityField key : entity.getKeys()) {
            location.append('/');
            if (STRING_TYPE.equals(key.getFieldType())) {
                location.append("${dataserviceEncodePathSegment(").append(key.getFieldName()).append(")}");
            } else {
                location.append("${").append(key.getFieldName()).append('}');
            }
        }
        return location.append('`').toString();
    }

    private static StringBuilder header() {
        return new StringBuilder(AUTOGENERATED_FILE_COMMENT).append(NEW_LINE).append(NEW_LINE)
                .append(AUTO_GENERATED_COMMENT).append(NEW_LINE)
                .append(COMMENT_SHOULD_NOT_BE_MODIFIED).append(NEW_LINE).append(NEW_LINE);
    }

    private static String format(String source) throws BalException {
        try {
            return Formatter.format(SyntaxTree.from(TextDocuments.from(source))).toSourceCode();
        } catch (FormatterException e) {
            throw new BalException("failed to format the data service source: " + e.getMessage());
        }
    }
}
