import ballerina/sql;
import ballerinax/mysql;
import ballerina/time;
import ballerina/persist;

public client class MedicalNeed1Client {

    private final string entityName = "MedicalNeed1";
    private final sql:ParameterizedQuery tableName = `MedicalNeeds1`;

    private final map<persist:FieldMetadata> fieldMetadata = {
        needId: {columnName: "needId", 'type: int, autoGenerated: true},
        itemId: {columnName: "itemId", 'type: int},
        beneficiaryId: {columnName: "beneficiaryId", 'type: int},
        period: {columnName: "period", 'type: time:Civil},
        urgency: {columnName: "urgency", 'type: string},
        quantity: {columnName: "quantity", 'type: int}
    };
    private string[] keyFields = ["needId"];

    private persist:SQLClient persistClient;

    public function init() returns error? {
        mysql:Client dbClient = check new (host = host, user = user, password = password, database = database, port = port);
        self.persistClient = check new (dbClient, self.entityName, self.tableName, self.keyFields, self.fieldMetadata);
    }

    remote function create(MedicalNeed1 value) returns MedicalNeed1|error {
        sql:ExecutionResult result = check self.persistClient.runInsertQuery(value);
        return {needId: <int>result.lastInsertId, itemId: value.itemId, beneficiaryId: value.beneficiaryId, period: value.period, urgency: value.urgency, quantity: value.quantity};
    }

    remote function readByKey(int key) returns MedicalNeed1|error {
        return (check self.persistClient.runReadByKeyQuery(MedicalNeed1, key)).cloneWithType(MedicalNeed1);
    }

    remote function read() returns stream<MedicalNeed1, error?> {
        stream<anydata, error?>|error result = self.persistClient.runReadQuery(MedicalNeed1, ());
        if result is error {
            return new stream<MedicalNeed1, error?>(new MedicalNeed1Stream((), result));
        } else {
            return new stream<MedicalNeed1, error?>(new MedicalNeed1Stream(result));
        }
    }

    remote function execute(sql:ParameterizedQuery filterClause) returns stream<MedicalNeed1, error?> {
        stream<anydata, error?>|error result = self.persistClient.runExecuteQuery(filterClause, MedicalNeed1);
        if result is error {
            return new stream<MedicalNeed1, error?>(new MedicalNeed1Stream((), result));
        } else {
            return new stream<MedicalNeed1, error?>(new MedicalNeed1Stream(result));
        }
    }

    remote function update(MedicalNeed1 value) returns error? {
        map<anydata> filter = {"needId": value.needId};
        _ = check self.persistClient.runUpdateQuery(value, filter);
    }

    remote function delete(MedicalNeed1 value) returns error? {
        _ = check self.persistClient.runDeleteQuery(value);
    }

    public function close() returns error? {
        return self.persistClient.close();
    }
}

public class MedicalNeed1Stream {

    private stream<anydata, error?>? anydataStream;
    private error? err;

    public isolated function init(stream<anydata, error?>? anydataStream, error? err = ()) {
        self.anydataStream = anydataStream;
        self.err = err;
    }

    public isolated function next() returns record {|MedicalNeed1 value;|}|error? {
        if self.err is error {
            return <error>self.err;
        } else if self.anydataStream is stream<anydata, error?> {
            var anydataStream = <stream<anydata, error?>>self.anydataStream;
            var streamValue = anydataStream.next();
            if streamValue is () {
                return streamValue;
            } else if (streamValue is error) {
                return streamValue;
            } else {
                record {|MedicalNeed1 value;|} nextRecord = {value: check streamValue.value.cloneWithType(MedicalNeed1)};
                return nextRecord;
            }
        } else {
            return ();
        }
    }

    public isolated function close() returns error? {
        if self.anydataStream is stream<anydata, error?> {
            var anydataStream = <stream<anydata, error?>>self.anydataStream;
            return anydataStream.close();
        }
    }
}

