/*
 * Copyright (c) 2022, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package io.ballerina.persist.nodegenerator;

import io.ballerina.compiler.syntax.tree.AbstractNodeFactory;
import io.ballerina.compiler.syntax.tree.ArrayDimensionNode;
import io.ballerina.compiler.syntax.tree.ArrayTypeDescriptorNode;
import io.ballerina.compiler.syntax.tree.BuiltinSimpleNameReferenceNode;
import io.ballerina.compiler.syntax.tree.FunctionDefinitionNode;
import io.ballerina.compiler.syntax.tree.IdentifierToken;
import io.ballerina.compiler.syntax.tree.ImportDeclarationNode;
import io.ballerina.compiler.syntax.tree.ImportOrgNameNode;
import io.ballerina.compiler.syntax.tree.ImportPrefixNode;
import io.ballerina.compiler.syntax.tree.MinutiaeList;
import io.ballerina.compiler.syntax.tree.ModuleMemberDeclarationNode;
import io.ballerina.compiler.syntax.tree.ModulePartNode;
import io.ballerina.compiler.syntax.tree.Node;
import io.ballerina.compiler.syntax.tree.NodeFactory;
import io.ballerina.compiler.syntax.tree.NodeList;
import io.ballerina.compiler.syntax.tree.NodeParser;
import io.ballerina.compiler.syntax.tree.OptionalTypeDescriptorNode;
import io.ballerina.compiler.syntax.tree.QualifiedNameReferenceNode;
import io.ballerina.compiler.syntax.tree.RecordFieldNode;
import io.ballerina.compiler.syntax.tree.RecordTypeDescriptorNode;
import io.ballerina.compiler.syntax.tree.SeparatedNodeList;
import io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode;
import io.ballerina.compiler.syntax.tree.SyntaxKind;
import io.ballerina.compiler.syntax.tree.SyntaxTree;
import io.ballerina.compiler.syntax.tree.Token;
import io.ballerina.compiler.syntax.tree.TypeDefinitionNode;
import io.ballerina.compiler.syntax.tree.TypeDescriptorNode;
import io.ballerina.persist.BalException;
import io.ballerina.persist.components.Client;
import io.ballerina.persist.components.ClientResource;
import io.ballerina.persist.components.Function;
import io.ballerina.persist.components.IfElse;
import io.ballerina.persist.components.TypeDescriptor;
import io.ballerina.persist.models.Entity;
import io.ballerina.persist.models.EntityField;
import io.ballerina.persist.models.Module;
import io.ballerina.persist.models.Relation;
import io.ballerina.tools.text.TextDocument;
import io.ballerina.tools.text.TextDocuments;
import org.ballerinalang.formatter.core.Formatter;
import org.ballerinalang.formatter.core.FormatterException;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;

import static io.ballerina.compiler.syntax.tree.SyntaxKind.QUALIFIED_NAME_REFERENCE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.ARRAY;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.ASSOCIATED_FIELD_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.AUTOGENERATED_FILE_COMMENT;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.AUTO_GENERATED_COMMENT;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.AUTO_GENERATED_COMMENT_WITH_REASON;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.BACK_SLASH;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.CLOSE_BRACE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.CLOSE_BRACKET;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.COLON;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.COLUMN_ARRAY_ENTRY_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.COMMA_SPACE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.COMMA_WITH_NEWLINE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.COMMENT_SHOULD_NOT_BE_MODIFIED;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.DB_CLIENT;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.DOUBLE_QUOTE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.EMPTY_STRING;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.EXTERNAL_GET_BY_KEY_METHOD_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.EXTERNAL_GET_METHOD_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.FIELD_METADATA_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.INIT_DBCLIENT;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.INIT_DB_CLIENT;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.INIT_PERSIST_CLIENT_MAP;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.INSERT_RECORD;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.JOIN_METADATA_FIELD_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.JOIN_METADATA_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.KEYWORD_BALLERINA;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.KEYWORD_BALLERINAX;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.KEYWORD_ISOLATED;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.KEYWORD_JBALLERINA_JAVA_PREFIX;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.KEYWORD_PERSIST;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.KEYWORD_READONLY;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.KEYWORD_VALUE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.METADATARECORD_ELEMENT_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.METADATARECORD_ENTITY_NAME_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.METADATARECORD_FIELD_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.METADATARECORD_KEY_FIELD_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.METADATARECORD_TABLE_NAME_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.METADATARECORD_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.MYSQL_DRIVER;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.OPEN_BRACE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.OPEN_BRACKET;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.PERSIST_CLIENT_CLOSE_STATEMENT;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.PERSIST_CLIENT_MAP_ELEMENT;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.PERSIST_CLIENT_TEMPLATE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.PERSIST_ERROR;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.PERSIST_MODULE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.QUESTION_MARK;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.REGEX_FOR_SPLIT_BY_CAPITOL_LETTER;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.RESULT;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.RESULT_IS_BALLERINA_ERROR;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.SELECT_WITH_SPACE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.SEMICOLON;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.SINGLE_QUOTE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.SPACE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.SPECIFIC_ERROR;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.UNDERSCORE;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.UPDATE_RECORD;
import static io.ballerina.persist.nodegenerator.BalSyntaxConstants.VALUE;
import static io.ballerina.persist.nodegenerator.SyntaxTokenConstants.SYNTAX_TREE_SEMICOLON;

/**
 * Class containing methods to create and read ballerina files as syntax trees.
 *
 * @since 0.1.0
 */
public class BalSyntaxGenerator {

    private BalSyntaxGenerator() {
    }

    /**
     * method to read ballerina files.
     */
    public static void populateEntities(Module.Builder moduleBuilder, SyntaxTree balSyntaxTree) throws IOException,
            BalException {
        ModulePartNode rootNote = balSyntaxTree.rootNode();
        NodeList<ModuleMemberDeclarationNode> nodeList = rootNote.members();
        rootNote.imports().stream().filter(importNode -> importNode.orgName().isPresent() && importNode.orgName().get()
                .orgName().text().equals(KEYWORD_BALLERINA) &&
                importNode.moduleName().stream().anyMatch(node -> node.text().equals(KEYWORD_PERSIST)))
                .findFirst().orElseThrow(() -> new BalException(
                        "no `import ballerina/persist as _;` statement found.."));

        Entity.Builder entityBuilder;
        for (ModuleMemberDeclarationNode moduleNode : nodeList) {
            if (moduleNode.kind() != SyntaxKind.TYPE_DEFINITION) {
                continue;
            }
            TypeDefinitionNode typeDefinitionNode = (TypeDefinitionNode) moduleNode;
            entityBuilder = Entity.newBuilder(typeDefinitionNode.typeName().text().trim());

            List<EntityField> keyArray = new ArrayList<>();
            RecordTypeDescriptorNode recordDesc = (RecordTypeDescriptorNode) ((TypeDefinitionNode) moduleNode)
                    .typeDescriptor();
            for (Node node : recordDesc.fields()) {
                EntityField.Builder fieldBuilder;
                RecordFieldNode fieldNode = (RecordFieldNode) node;
                fieldBuilder = EntityField.newBuilder(fieldNode.fieldName().text().trim());
                TypeDescriptorNode type;
                Node fieldType = fieldNode.typeName();
                if (fieldType instanceof OptionalTypeDescriptorNode) {
                    fieldBuilder.setOptionalType(true);
                    fieldType = ((OptionalTypeDescriptorNode) fieldType).typeDescriptor();
                }
                if (fieldType instanceof ArrayTypeDescriptorNode) {
                    type = ((ArrayTypeDescriptorNode) fieldType).memberTypeDesc();
                    fieldBuilder.setArrayType(true);
                } else {
                    type = (TypeDescriptorNode) fieldType;
                }
                String fType = getType(type, fieldNode.fieldName().text().trim());
                String qualifiedNamePrefix = getQualifiedModulePrefix(type);
                fieldBuilder.setType(fType);
                fieldBuilder.setOptionalType(fieldNode.typeName().kind().equals(SyntaxKind.OPTIONAL_TYPE_DESC));
                EntityField entityField = fieldBuilder.build();
                entityBuilder.addField(entityField);
                if (fieldNode.readonlyKeyword().isPresent()) {
                    keyArray.add(entityField);
                }

                if (qualifiedNamePrefix != null) {
                    moduleBuilder.addImportModulePrefix(qualifiedNamePrefix);
                }
            }
            entityBuilder.setKeys(keyArray);
            Entity entity = entityBuilder.build();
            moduleBuilder.addEntity(entity.getEntityName(), entity);
        }
    }

    private static String getType(TypeDescriptorNode typeDesc, String fieldName) throws BalException {
        switch (typeDesc.kind()) {
            case INT_TYPE_DESC:
            case BOOLEAN_TYPE_DESC:
            case DECIMAL_TYPE_DESC:
            case FLOAT_TYPE_DESC:
            case STRING_TYPE_DESC:
            case BYTE_TYPE_DESC:
                return ((BuiltinSimpleNameReferenceNode) typeDesc).name().text();
            case QUALIFIED_NAME_REFERENCE:
                QualifiedNameReferenceNode qualifiedName = (QualifiedNameReferenceNode) typeDesc;
                String modulePrefix = qualifiedName.modulePrefix().text();
                String identifier = qualifiedName.identifier().text();
                return modulePrefix + COLON + identifier;
            case SIMPLE_NAME_REFERENCE:
                return ((SimpleNameReferenceNode) typeDesc).name().text();
            case OPTIONAL_TYPE_DESC:
                return getType((TypeDescriptorNode) ((OptionalTypeDescriptorNode) typeDesc).typeDescriptor(),
                        fieldName);
            default:
                throw new BalException(String.format("unsupported data type found for the field `%s`", fieldName));
        }
    }

    private static String getQualifiedModulePrefix(TypeDescriptorNode typeDesc) {
        if (typeDesc.kind() == QUALIFIED_NAME_REFERENCE) {
            QualifiedNameReferenceNode qualifiedName = (QualifiedNameReferenceNode) typeDesc;
            return qualifiedName.modulePrefix().text();
        } else {
            return null;
        }
    }

    public static void inferRelationDetails(Module entityModule) {
        Map<String, Entity> entityMap = entityModule.getEntityMap();
        for (Entity entity : entityMap.values()) {
            List<EntityField> fields = entity.getFields();
            fields.stream().filter(field -> entityMap.get(field.getFieldType()) != null)
                    .forEach(field -> {
                        String fieldType = field.getFieldType();
                        Entity assocEntity = entityMap.get(fieldType);
                        if (field.getRelation() == null) {
                            // this branch only handles one-to-one or one-to-many or many-to-many with no relation
                            // annotations
                            assocEntity.getFields().stream().filter(assocfield -> assocfield.getFieldType()
                                    .equals(entity.getEntityName()))
                                    .filter(assocfield -> assocfield.getRelation() == null).forEach(assocfield -> {
                                        // one-to-many or many-to-many with no relation annotations
                                        if (field.isArrayType() && assocfield.isArrayType()) {
                                            throw new RuntimeException("unsupported many to many relation between " +
                                                    entity.getEntityName() + " and " + assocEntity.getEntityName());
                                        }
                                        // one-to-one
                                        if (!field.isArrayType() && !assocfield.isArrayType()) {
                                            field.setRelation(computeRelation(entity, assocEntity, true,
                                                    Relation.RelationType.ONE));
                                            assocfield.setRelation(computeRelation(assocEntity, entity, false,
                                                    Relation.RelationType.ONE));
                                        } else {
                                            if (field.isArrayType() && field.isOptionalType()) {
                                                // one-to-many relation. associated entity is the owner.
                                                field.setRelation(computeRelation(entity, assocEntity, false,
                                                        Relation.RelationType.MANY));
                                                assocfield.setRelation(computeRelation(assocEntity, entity, true,
                                                        Relation.RelationType.ONE));
                                            } else if (field.isArrayType() || field.getFieldType().equals("byte")) {
                                                field.setRelation(null);
                                            } else {
                                                // one-to-many relation. entity is the owner.
                                                // one-to-one relation. entity is the owner.
                                                field.setRelation(computeRelation(entity, assocEntity, true,
                                                        Relation.RelationType.ONE));
                                                assocfield.setRelation(computeRelation(assocEntity, entity,
                                                        false, Relation.RelationType.MANY));
                                            }
                                        }
                                    });
                        } else if (field.getRelation() != null && field.getRelation().isOwner()) {
                            field.getRelation().setRelationType(
                                    field.isArrayType() ? Relation.RelationType.MANY : Relation.RelationType.ONE);
                            field.getRelation().setAssocEntity(assocEntity);
                            List<Relation.Key> keyColumns = field.getRelation().getKeyColumns();
                            if (keyColumns == null || keyColumns.size() == 0) {
                                keyColumns = assocEntity.getKeys().stream()
                                        .map(key -> new Relation.Key(
                                                assocEntity.getEntityName().toLowerCase(Locale.ENGLISH)
                                                        + stripEscapeCharacter(key.getFieldName()).substring(0, 1)
                                                                .toUpperCase(Locale.ENGLISH)
                                                        + stripEscapeCharacter(key.getFieldName()).substring(1),
                                                key.getFieldName(), key.getFieldType()))
                                        .collect(Collectors.toList());
                                field.getRelation().setKeyColumns(keyColumns);
                            }
                            List<String> references = field.getRelation().getReferences();
                            if (references == null || references.size() == 0) {
                                field.getRelation().setReferences(assocEntity.getKeys().stream()
                                        .map(EntityField::getFieldName)
                                        .collect(Collectors.toList()));
                            }

                            // create bidirectional mapping for associated entity
                            Relation.Builder assocRelBuilder = Relation.newBuilder();
                            assocRelBuilder.setOwner(false);
                            assocRelBuilder.setAssocEntity(entity);

                            List<Relation.Key> assockeyColumns = assocEntity
                                    .getKeys().stream().map(key -> new Relation.Key(key.getFieldName(),
                                            assocEntity.getEntityName().toLowerCase(Locale.ENGLISH)
                                                    + stripEscapeCharacter(key.getFieldName()).substring(0, 1)
                                                            .toUpperCase(Locale.ENGLISH)
                                                    + stripEscapeCharacter(key.getFieldName()).substring(1),
                                            key.getFieldType()))
                                    .collect(Collectors.toList());
                            assocRelBuilder.setKeys(assockeyColumns);
                            assocRelBuilder.setReferences(assockeyColumns.stream().map(Relation.Key::getReference)
                                    .collect(Collectors.toList()));
                            assocEntity.getFields().stream().filter(assocfield -> assocfield.getFieldType()
                                    .equals(entity.getEntityName())).forEach(
                                            assocField -> {
                                                assocRelBuilder.setRelationType(
                                                        assocField.isArrayType() ? Relation.RelationType.MANY
                                                                : Relation.RelationType.ONE);
                                                assocField.setRelation(assocRelBuilder.build());
                                            });
                        }
                    });
        }
    }

    private static Relation computeRelation(Entity entity, Entity assocEntity, boolean isOwner,
                                            Relation.RelationType relationType) {
        Relation.Builder relBuilder = new Relation.Builder();
        relBuilder.setAssocEntity(assocEntity);
        if (isOwner) {
            List<Relation.Key> keyColumns = assocEntity.getKeys().stream().map(key ->
                    new Relation.Key(stripEscapeCharacter(assocEntity.getEntityName().toLowerCase(Locale.ENGLISH))
                            + stripEscapeCharacter(key.getFieldName()).substring(0, 1).toUpperCase(Locale.ENGLISH)
                            + stripEscapeCharacter(key.getFieldName()).substring(1), key.getFieldName(),
                            key.getFieldType())).collect(Collectors.toList());
            relBuilder.setOwner(true);
            relBuilder.setRelationType(relationType);
            relBuilder.setKeys(keyColumns);
            relBuilder.setReferences(assocEntity.getKeys().stream().map(EntityField::getFieldName)
                    .collect(Collectors.toList()));
        } else {
            List<Relation.Key> keyColumns = entity.getKeys().stream().map(key -> new Relation.Key(key.getFieldName(),
                    entity.getEntityName().toLowerCase(Locale.ENGLISH)
                            + stripEscapeCharacter(key.getFieldName()).substring(0, 1).toUpperCase(Locale.ENGLISH)
                            + stripEscapeCharacter(key.getFieldName()).substring(1),
                    key.getFieldType()))
                    .collect(Collectors.toList());
            relBuilder.setOwner(false);
            relBuilder.setRelationType(relationType);
            relBuilder.setKeys(keyColumns);
            relBuilder.setReferences(keyColumns.stream().map(Relation.Key::getReference).collect(Collectors.toList()));
        }
        return relBuilder.build();
    }

    public static SyntaxTree generateClientSyntaxTree(Module entityModule) throws BalException {
        NodeList<ImportDeclarationNode> imports = AbstractNodeFactory.createEmptyNodeList();
        NodeList<ModuleMemberDeclarationNode> moduleMembers = AbstractNodeFactory.createEmptyNodeList();

        MinutiaeList commentMinutiaeList = createCommentMinutiaeList(String.format(AUTO_GENERATED_COMMENT_WITH_REASON,
                entityModule.getModuleName()));
        imports = imports.add(getImportDeclarationNodeWithAutogeneratedComment(KEYWORD_BALLERINA,
                BalSyntaxConstants.PERSIST_MODULE, commentMinutiaeList, null));
        imports = imports.add(getImportDeclarationNode(BalSyntaxConstants.KEYWORD_BALLERINA,
                KEYWORD_JBALLERINA_JAVA_PREFIX, null));
        imports = imports.add(getImportDeclarationNode(BalSyntaxConstants.KEYWORD_BALLERINAX,
                BalSyntaxConstants.KEYWORD_MYSQL, null));

        for (Entity entity : entityModule.getEntityMap().values()) {
            moduleMembers = moduleMembers.add(NodeParser.parseModuleMemberDeclaration(String.format(
                    "const %s = \"%s\";", getEntityNameConstant(entity.getEntityName()),
                            stripEscapeCharacter(entity.getResourceName()))));
        }

        Client clientObject = createClient(entityModule);
        moduleMembers = moduleMembers.add(clientObject.getClassDefinitionNode());

        Token eofToken = AbstractNodeFactory.createIdentifierToken(EMPTY_STRING);
        ModulePartNode modulePartNode = NodeFactory.createModulePartNode(imports, moduleMembers, eofToken);
        TextDocument textDocument = TextDocuments.from(EMPTY_STRING);
        SyntaxTree balTree = SyntaxTree.from(textDocument);
        return balTree.modifyWith(modulePartNode);
    }

    private static Client createClient(Module entityModule) throws BalException {
        Client clientObject = new Client("Client", true);
        clientObject.addQualifiers(new String[] { BalSyntaxConstants.KEYWORD_CLIENT });
        clientObject.addMember(NodeFactory.createTypeReferenceNode(
                AbstractNodeFactory.createToken(SyntaxKind.ASTERISK_TOKEN),
                NodeFactory.createQualifiedNameReferenceNode(
                        NodeFactory.createIdentifierToken(
                                BalSyntaxConstants.InheritedTypeReferenceConstants.PERSIST_MODULE_NAME),
                        AbstractNodeFactory.createToken(SyntaxKind.COLON_TOKEN),
                        NodeFactory.createIdentifierToken(
                                BalSyntaxConstants.InheritedTypeReferenceConstants.ABSTRACT_PERSIST_CLIENT)),
                AbstractNodeFactory.createToken(SyntaxKind.SEMICOLON_TOKEN)), false);
        clientObject.addMember(NodeParser.parseObjectMember(INIT_DB_CLIENT), true);
        clientObject.addMember(NodeParser.parseObjectMember(INIT_PERSIST_CLIENT_MAP), true);
        clientObject.addMember(generateMetadataRecord(entityModule), true);

        Collection<Entity> entityArray = entityModule.getEntityMap().values();
        if (entityArray.size() == 0) {
            throw new BalException("data definition file() does not contain any entities.");
        }
        Function init = createInitFunction(entityArray);
        clientObject.addMember(init.getFunctionDefinitionNode(), true);
        List<ClientResource> resourceList = new ArrayList<>();
        for (Entity entity : entityArray) {
            resourceList.add(createClientResource(entity));
        }
        resourceList.forEach(resource -> {
            resource.getFunctions().forEach(function -> {
                clientObject.addMember(function, false);
            });
        });
        clientObject.addMember(createClientCloseFunction().getFunctionDefinitionNode(), true);
        return clientObject;
    }

    private static Node generateMetadataRecord(Module entityModule) {
        StringBuilder mapBuilder = new StringBuilder();
        for (Entity entity : entityModule.getEntityMap().values()) {
            if (mapBuilder.length() != 0) {
                mapBuilder.append(COMMA_WITH_NEWLINE);
            }
            StringBuilder entityMetaData = new StringBuilder();
            entityMetaData.append(String.format(METADATARECORD_ENTITY_NAME_TEMPLATE,
                    stripEscapeCharacter(entity.getEntityName())));
            entityMetaData.append(String.format(METADATARECORD_TABLE_NAME_TEMPLATE,
                    stripEscapeCharacter(entity.getEntityName())));
            StringBuilder fieldMetaData = new StringBuilder();
            StringBuilder associateFieldMEtaData = new StringBuilder();
            boolean relationsExists = false;
            for (EntityField field : entity.getFields()) {
                if (field.getRelation() != null) {
                    relationsExists = true;
                    StringBuilder foreignKeyFields = new StringBuilder();
                    if (field.getRelation().isOwner()) {
                        if (fieldMetaData.length() != 0) {
                            fieldMetaData.append(COMMA_WITH_NEWLINE);
                        }
                        for (Relation.Key key : field.getRelation().getKeyColumns()) {
                            if (foreignKeyFields.length() != 0) {
                                foreignKeyFields.append(COMMA_WITH_NEWLINE);
                            }
                            foreignKeyFields.append(String.format(METADATARECORD_FIELD_TEMPLATE,
                                    key.getField(), stripEscapeCharacter(key.getField())));
                        }
                    }
                    fieldMetaData.append(foreignKeyFields);
                    Entity associatedEntity = field.getRelation().getAssocEntity();
                    for (EntityField associatedEntityField : associatedEntity.getFields()) {
                        if (associatedEntityField.getRelation() == null) {
                            if (associateFieldMEtaData.length() != 0) {
                                associateFieldMEtaData.append(COMMA_WITH_NEWLINE);
                            }
                            associateFieldMEtaData.append(String.format((field.isArrayType() ? "\"%s[]" : "\"%s") +
                                            ASSOCIATED_FIELD_TEMPLATE,
                                    field.getFieldName(),
                                    associatedEntityField.getFieldName(), stripEscapeCharacter(field.getFieldName()),
                                    stripEscapeCharacter(associatedEntityField.getFieldName())));
                        } else {
                            if (associatedEntityField.getRelation().isOwner()) {
                                for (Relation.Key key : associatedEntityField.getRelation().getKeyColumns()) {
                                    if (associateFieldMEtaData.length() != 0) {
                                        associateFieldMEtaData.append(COMMA_WITH_NEWLINE);
                                    }
                                    associateFieldMEtaData.append(String.format((field.isArrayType() ?
                                                    "\"%s[]" : "\"%s") +
                                                    ASSOCIATED_FIELD_TEMPLATE,
                                            field.getFieldName(), key.getField(),
                                            stripEscapeCharacter(associatedEntityField.getFieldName()),
                                            stripEscapeCharacter(key.getField())));
                                }
                            }
                        }
                    }
                } else {
                    if (fieldMetaData.length() != 0) {
                        fieldMetaData.append(COMMA_WITH_NEWLINE);
                    }
                    fieldMetaData.append(String.format(METADATARECORD_FIELD_TEMPLATE,
                            field.getFieldName(), stripEscapeCharacter(field.getFieldName()),
                            stripEscapeCharacter(field.getFieldType())));
                }
            }
            if (associateFieldMEtaData.length() > 1) {
                fieldMetaData.append(",");
                fieldMetaData.append(associateFieldMEtaData);
            }
            entityMetaData.append(String.format(FIELD_METADATA_TEMPLATE, fieldMetaData));
            entityMetaData.append(COMMA_SPACE);

            StringBuilder keyFields = new StringBuilder();
            for (EntityField key : entity.getKeys()) {
                if (keyFields.length() != 0) {
                    keyFields.append(COMMA_SPACE);
                }
                keyFields.append("\"").append(stripEscapeCharacter(key.getFieldName())).append("\"");
            }
            entityMetaData.append(String.format(METADATARECORD_KEY_FIELD_TEMPLATE, keyFields));
            if (relationsExists) {
                entityMetaData.append(COMMA_SPACE);
                String joinMetaData = getJoinMetaData(entity);
                entityMetaData.append(String.format(JOIN_METADATA_TEMPLATE, joinMetaData));
            }

            mapBuilder.append(String.format(METADATARECORD_ELEMENT_TEMPLATE,
                    entity.getResourceName(), entityMetaData));
        }
        return NodeParser.parseObjectMember(String.format(METADATARECORD_TEMPLATE, mapBuilder));
    }

    private static String getJoinMetaData(Entity entity) {
        StringBuilder joinMetaData = new StringBuilder();
        StringBuilder refColumns = new StringBuilder();
        StringBuilder joinColumns = new StringBuilder();
        for (EntityField entityField : entity.getFields()) {
            if (entityField.getRelation() != null) {
                String relationType = "persist:ONE_TO_ONE";
                Entity associatedEntity = entityField.getRelation().getAssocEntity();
                for (EntityField associatedEntityField : associatedEntity.getFields()) {
                    if (associatedEntityField.getFieldType().equals(entity.getEntityName())) {
                        if (associatedEntityField.isArrayType() && !entityField.isArrayType()) {
                            relationType = "persist:ONE_TO_MANY";
                        } else if (!associatedEntityField.isArrayType() && entityField.isArrayType()) {
                            relationType = "persist:MANY_TO_ONE";
                        } else if (associatedEntityField.isArrayType() && entityField.isArrayType()) {
                            relationType = "persist:MANY_TO_MANY";
                        }
                    }
                }
            if (joinMetaData.length() > 0) {
                joinMetaData.append(COMMA_WITH_NEWLINE);
            }
            for (Relation.Key key : entityField.getRelation().getKeyColumns()) {
                if (joinColumns.length() > 0) {
                    joinColumns.append(",");
                }
                if (refColumns.length() > 0) {
                    refColumns.append(",");
                }
                refColumns.append(String.format(COLUMN_ARRAY_ENTRY_TEMPLATE, key.getReference()));
                joinColumns.append(String.format(COLUMN_ARRAY_ENTRY_TEMPLATE, key.getField()));
            }
            joinMetaData.append(String.format(JOIN_METADATA_FIELD_TEMPLATE, entityField.getFieldName(),
                    entityField.getFieldType(),
                    entityField.getFieldName(), entityField.getFieldType(), refColumns,
                    joinColumns, relationType));
            }
        }
        return joinMetaData.toString();
    }

    private static ClientResource createClientResource(Entity entity) {
        HashMap<String, String> keys = new HashMap<>();
        ClientResource resource = new ClientResource(entity.getResourceName());
        for (EntityField field : entity.getKeys()) {
            keys.put(field.getFieldName(), field.getFieldType());
        }
        resource.addFunction(createGetFunction(entity), true);

        resource.addFunction(createGetByKeyFunction(entity, keys), true);

        Function create = createPostFunction(entity);
        resource.addFunction(create.getFunctionDefinitionNode(), true);

        Function update = createPutFunction(entity, keys);
        resource.addFunction(update.getFunctionDefinitionNode(), true);

        Function delete = createDeleteFunction(entity, keys);
        resource.addFunction(delete.getFunctionDefinitionNode(), true);

        return resource;
    }

    private static Function createInitFunction(Collection<Entity> entityArray) {
        Function init = new Function(BalSyntaxConstants.INIT, SyntaxKind.OBJECT_METHOD_DEFINITION);
        init.addQualifiers(new String[] { BalSyntaxConstants.KEYWORD_PUBLIC });
        init.addReturns(TypeDescriptor.getOptionalTypeDescriptorNode(EMPTY_STRING,
                PERSIST_ERROR));
        init.addStatement(NodeParser.parseStatement(INIT_DBCLIENT));
        IfElse errorCheck = new IfElse(NodeParser.parseExpression(String.format(RESULT_IS_BALLERINA_ERROR, DB_CLIENT)));
        errorCheck.addIfStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.RETURN_ERROR, DB_CLIENT)));
        init.addIfElseStatement(errorCheck.getIfElseStatementNode());
        init.addStatement(NodeParser.parseStatement(BalSyntaxConstants.ADD_CLIENT));
        StringBuilder persistClientMap = new StringBuilder();
        for (Entity entity : entityArray) {
            if (persistClientMap.length() != 0) {
                persistClientMap.append(COMMA_WITH_NEWLINE);
            }
            persistClientMap.append(String.format(PERSIST_CLIENT_MAP_ELEMENT,
                    entity.getResourceName(), getEntityNameConstant(entity.getEntityName())));
        }
        init.addStatement(NodeParser.parseStatement(String.format(PERSIST_CLIENT_TEMPLATE, persistClientMap)));
        return init;
    }

    private static Function createClientCloseFunction() {
        Function close = new Function(BalSyntaxConstants.CLOSE, SyntaxKind.OBJECT_METHOD_DEFINITION);
        close.addQualifiers(new String[] { BalSyntaxConstants.KEYWORD_PUBLIC });
        close.addReturns(TypeDescriptor.getOptionalTypeDescriptorNode(EMPTY_STRING,
                PERSIST_ERROR));
        close.addStatement(NodeParser.parseStatement(PERSIST_CLIENT_CLOSE_STATEMENT));
        IfElse errorCheck = new IfElse(NodeParser.parseExpression(String.format(RESULT_IS_BALLERINA_ERROR, RESULT)));
        errorCheck.addIfStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.RETURN_ERROR, RESULT)));
        close.addIfElseStatement(errorCheck.getIfElseStatementNode());
        close.addStatement(NodeParser.parseStatement(BalSyntaxConstants.RETURN_RESULT));
        return close;
    }

    private static Function createPostFunction(Entity entity) {
        List<EntityField> primaryKeys = entity.getKeys();
        String parameterType = String.format(INSERT_RECORD, entity.getEntityName());

        Function create = new Function(BalSyntaxConstants.POST, SyntaxKind.RESOURCE_ACCESSOR_DEFINITION);
        NodeList<Node> resourcePaths = AbstractNodeFactory.createEmptyNodeList();
        resourcePaths = resourcePaths.add(AbstractNodeFactory.createIdentifierToken(entity.getResourceName()));
        create.addRelativeResourcePaths(resourcePaths);
        create.addRequiredParameter(
                TypeDescriptor.getArrayTypeDescriptorNode(parameterType), KEYWORD_VALUE);
        create.addQualifiers(new String[] { KEYWORD_ISOLATED, BalSyntaxConstants.KEYWORD_RESOURCE });
        addReturnsToPostResourceSignature(create, primaryKeys);
        addFunctionBodyToPostResource(create, primaryKeys,
                getEntityNameConstant(entity.getEntityName()), parameterType);
        return create;
    }

    private static void addReturnsToPostResourceSignature(Function create, List<EntityField> primaryKeys) {
        ArrayDimensionNode arrayDimensionNode = NodeFactory.createArrayDimensionNode(
                SyntaxTokenConstants.SYNTAX_TREE_OPEN_BRACKET,
                null,
                SyntaxTokenConstants.SYNTAX_TREE_CLOSE_BRACKET);
        NodeList<ArrayDimensionNode> dimensionList = NodeFactory.createNodeList(arrayDimensionNode);
        List<Node> typeTuple = new ArrayList<>();
        if (primaryKeys.size() > 1) {
            primaryKeys.forEach(primaryKey -> {
                if (!typeTuple.isEmpty()) {
                    typeTuple.add(NodeFactory.createToken(SyntaxKind.COMMA_TOKEN));
                }
                typeTuple.add(NodeFactory.createSimpleNameReferenceNode(
                        NodeFactory.createIdentifierToken(primaryKey.getFieldType())));
            });
            create.addReturns(TypeDescriptor.getUnionTypeDescriptorNode(
                    NodeFactory.createArrayTypeDescriptorNode(NodeFactory.createTupleTypeDescriptorNode(
                            NodeFactory.createToken(SyntaxKind.OPEN_BRACKET_TOKEN),
                            NodeFactory.createSeparatedNodeList(typeTuple),
                            NodeFactory.createToken(SyntaxKind.CLOSE_BRACKET_TOKEN)), dimensionList),
                    TypeDescriptor.getQualifiedNameReferenceNode(PERSIST_MODULE, SPECIFIC_ERROR)));
        } else {
            create.addReturns(TypeDescriptor.getUnionTypeDescriptorNode(
                    TypeDescriptor.getArrayTypeDescriptorNode(primaryKeys.get(0).getFieldType()),
                    TypeDescriptor.getQualifiedNameReferenceNode(PERSIST_MODULE, SPECIFIC_ERROR)));

        }
    }

    private static void addFunctionBodyToPostResource(Function create, List<EntityField> primaryKeys,
            String tableName, String parameterType) {
        create.addStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.CREATE_SQL_RESULTS,
                tableName)));
        create.addStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.RETURN_CREATED_KEY,
                parameterType)));
        StringBuilder filterKeys = new StringBuilder();
        for (int i = 0; i < primaryKeys.size(); i++) {
            filterKeys.append("inserted.").append(primaryKeys.get(i).getFieldName());
            if (i < primaryKeys.size() - 1) {
                filterKeys.append(",");
            }
        }
        if (primaryKeys.size() == 1) {
            filterKeys = new StringBuilder(SELECT_WITH_SPACE + filterKeys + SEMICOLON);
        } else {
            filterKeys = new StringBuilder(SELECT_WITH_SPACE + OPEN_BRACKET + filterKeys + CLOSE_BRACKET + SEMICOLON);
        }
        create.addStatement(NodeParser.parseStatement(filterKeys.toString()));
    }

    private static FunctionDefinitionNode createGetByKeyFunction(Entity entity, HashMap<String, String> keys) {
        StringBuilder keyBuilder = new StringBuilder();
        for (Map.Entry<String, String> key : keys.entrySet()) {
            if (keyBuilder.length() > 0) {
                keyBuilder.append("/");
            }
            keyBuilder.append(OPEN_BRACKET);
            keyBuilder.append(key.getValue());
            keyBuilder.append(SPACE);
            keyBuilder.append(key.getKey());
            keyBuilder.append(CLOSE_BRACKET);
        }

        return (FunctionDefinitionNode) NodeParser.parseObjectMember(
                String.format(EXTERNAL_GET_BY_KEY_METHOD_TEMPLATE,
                        entity.getResourceName(), keyBuilder, entity.getEntityName()));
    }

    private static FunctionDefinitionNode createGetFunction(Entity entity) {
        return (FunctionDefinitionNode) NodeParser.parseObjectMember(
                String.format(EXTERNAL_GET_METHOD_TEMPLATE,
                        entity.getResourceName(), entity.getEntityName()));
    }

    private static Function createPutFunction(Entity entity, HashMap<String, String> keys) {
        Function update = new Function(BalSyntaxConstants.PUT, SyntaxKind.RESOURCE_ACCESSOR_DEFINITION);
        update.addQualifiers(new String[] { KEYWORD_ISOLATED, BalSyntaxConstants.KEYWORD_RESOURCE });
        update.addRequiredParameter(TypeDescriptor.getSimpleNameReferenceNode(
                String.format(UPDATE_RECORD, entity.getEntityName())), VALUE);
        NodeList<Node> resourcePaths = AbstractNodeFactory.createEmptyNodeList();
        StringBuilder filterKeys = new StringBuilder(OPEN_BRACE);
        StringBuilder path = new StringBuilder(BACK_SLASH + entity.getResourceName());
        resourcePaths = getResourcePath(resourcePaths, keys, filterKeys, path, entity.getResourceName());
        update.addRelativeResourcePaths(resourcePaths);
        update.addReturns(TypeDescriptor.getUnionTypeDescriptorNode(
                TypeDescriptor.getSimpleNameReferenceNode(entity.getEntityName()),
                TypeDescriptor.getQualifiedNameReferenceNode(PERSIST_MODULE, SPECIFIC_ERROR)));
        if (entity.getKeys().size() > 1) {
            update.addStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.UPDATE_RUN_UPDATE_QUERY,
                    getEntityNameConstant(entity.getEntityName()),
                    filterKeys.substring(0, filterKeys.length() - 2).concat(CLOSE_BRACE))));
        } else {
            update.addStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.UPDATE_RUN_UPDATE_QUERY,
                    getEntityNameConstant(entity.getEntityName()), entity.getKeys().stream().findFirst().get()
                            .getFieldName())));
        }
        update.addStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.UPDATE_RETURN_UPDATE_QUERY,
                path)));
        return update;
    }

    private static Function createDeleteFunction(Entity entity, HashMap<String, String> keys) {
        Function delete = new Function(BalSyntaxConstants.DELETE, SyntaxKind.RESOURCE_ACCESSOR_DEFINITION);
        delete.addQualifiers(new String[] { KEYWORD_ISOLATED, BalSyntaxConstants.KEYWORD_RESOURCE });
        NodeList<Node> resourcePaths = AbstractNodeFactory.createEmptyNodeList();
        StringBuilder path = new StringBuilder(BACK_SLASH + entity.getResourceName());
        StringBuilder filterKeys = new StringBuilder(OPEN_BRACE);
        resourcePaths = getResourcePath(resourcePaths, keys, filterKeys, path, entity.getResourceName());
        delete.addRelativeResourcePaths(resourcePaths);
        delete.addReturns(TypeDescriptor.getUnionTypeDescriptorNode(
                TypeDescriptor.getSimpleNameReferenceNode(entity.getEntityName()),
                TypeDescriptor.getQualifiedNameReferenceNode(PERSIST_MODULE, SPECIFIC_ERROR)));
        delete.addStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.GET_OBJECT_QUERY,
                entity.getEntityName(), path)));
        if (entity.getKeys().size() > 1) {
            delete.addStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.DELETE_RUN_DELETE_QUERY,
                    getEntityNameConstant(entity.getEntityName()),
                    filterKeys.substring(0, filterKeys.length() - 2).concat(CLOSE_BRACE))));
        } else {
            delete.addStatement(NodeParser.parseStatement(String.format(BalSyntaxConstants.DELETE_RUN_DELETE_QUERY,
                    getEntityNameConstant(entity.getEntityName()), entity.getKeys().stream().findFirst().get()
                            .getFieldName())));
        }
        delete.addStatement(NodeParser.parseStatement(BalSyntaxConstants.RETURN_DELETED_OBJECT));
        return delete;
    }

    private static NodeList<Node> getResourcePath(NodeList<Node> resourcePaths, HashMap<String, String> keys,
            StringBuilder filterKeys, StringBuilder path, String tableName) {
        resourcePaths = resourcePaths.add(AbstractNodeFactory.createIdentifierToken(tableName));
        for (Map.Entry<String, String> entry : keys.entrySet()) {
            resourcePaths = resourcePaths.add(AbstractNodeFactory.createToken(SyntaxKind.SLASH_TOKEN));
            resourcePaths = resourcePaths.add(NodeFactory.createResourcePathParameterNode(
                    SyntaxKind.RESOURCE_PATH_SEGMENT_PARAM,
                    AbstractNodeFactory.createToken(SyntaxKind.OPEN_BRACKET_TOKEN),
                    AbstractNodeFactory.createEmptyNodeList(),
                    NodeFactory.createBuiltinSimpleNameReferenceNode(SyntaxKind.STRING_TYPE_DESC,
                            AbstractNodeFactory.createIdentifierToken(entry.getValue() + SPACE)),
                    null,
                    AbstractNodeFactory.createIdentifierToken(entry.getKey()),
                    AbstractNodeFactory.createToken(SyntaxKind.CLOSE_BRACKET_TOKEN)));
            filterKeys.append(DOUBLE_QUOTE).append(stripEscapeCharacter(entry.getKey()))
                    .append(DOUBLE_QUOTE).append(COLON).append(entry.getKey()).append(COMMA_SPACE);
            path.append(BACK_SLASH).append(OPEN_BRACKET).append(entry.getKey()).append(CLOSE_BRACKET);
        }
        return resourcePaths;
    }

    public static SyntaxTree generateDatabaseConfigSyntaxTree() throws FormatterException {
        NodeList<ImportDeclarationNode> imports = AbstractNodeFactory.createEmptyNodeList();
        NodeList<ModuleMemberDeclarationNode> moduleMembers = AbstractNodeFactory.createEmptyNodeList();

        MinutiaeList commentMinutiaeList = createCommentMinutiaeList(String.format(AUTO_GENERATED_COMMENT));
        ImportPrefixNode prefix = NodeFactory.createImportPrefixNode(SyntaxTokenConstants.SYNTAX_TREE_AS,
                AbstractNodeFactory.createToken(SyntaxKind.UNDERSCORE_KEYWORD));
        imports = imports.add(getImportDeclarationNodeWithAutogeneratedComment(KEYWORD_BALLERINAX, MYSQL_DRIVER,
                commentMinutiaeList, prefix));
        moduleMembers = moduleMembers.add(NodeParser.parseModuleMemberDeclaration(
                BalSyntaxConstants.CONFIGURABLE_PORT));
        moduleMembers = moduleMembers.add(NodeParser.parseModuleMemberDeclaration(
                BalSyntaxConstants.CONFIGURABLE_HOST));
        moduleMembers = moduleMembers.add(NodeParser.parseModuleMemberDeclaration(
                BalSyntaxConstants.CONFIGURABLE_USER));
        moduleMembers = moduleMembers.add(NodeParser.parseModuleMemberDeclaration(
                BalSyntaxConstants.CONFIGURABLE_DATABASE));
        moduleMembers = moduleMembers.add(NodeParser.parseModuleMemberDeclaration(
                BalSyntaxConstants.CONFIGURABLE_PASSWORD));

        Token eofToken = AbstractNodeFactory.createIdentifierToken(EMPTY_STRING);
        ModulePartNode modulePartNode = NodeFactory.createModulePartNode(imports, moduleMembers, eofToken);
        TextDocument textDocument = TextDocuments.from(EMPTY_STRING);
        SyntaxTree balTree = SyntaxTree.from(textDocument);

        return balTree.modifyWith(modulePartNode);
    }

    public static String generateSchemaSyntaxTree() throws FormatterException {
        NodeList<ImportDeclarationNode> imports = AbstractNodeFactory.createEmptyNodeList();
        NodeList<ModuleMemberDeclarationNode> moduleMembers = AbstractNodeFactory.createEmptyNodeList();

        imports = imports.add(NodeParser.parseImportDeclaration("import ballerina/persist as _;"));
        Token eofToken = AbstractNodeFactory.createIdentifierToken(EMPTY_STRING);
        ModulePartNode modulePartNode = NodeFactory.createModulePartNode(imports, moduleMembers, eofToken);
        TextDocument textDocument = TextDocuments.from(EMPTY_STRING);
        SyntaxTree balTree = SyntaxTree.from(textDocument);

        // output cannot be SyntaxTree as it will overlap with Toml Syntax Tree in Init
        // Command
        return Formatter.format(balTree.modifyWith(modulePartNode).toSourceCode());
    }

    private static ImportDeclarationNode getImportDeclarationNode(String orgName, String moduleName,
            ImportPrefixNode prefix) {
        Token orgNameToken = AbstractNodeFactory.createIdentifierToken(orgName);
        ImportOrgNameNode importOrgNameNode = NodeFactory.createImportOrgNameNode(
                orgNameToken,
                SyntaxTokenConstants.SYNTAX_TREE_SLASH);
        Token moduleNameToken = AbstractNodeFactory.createIdentifierToken(moduleName);
        SeparatedNodeList<IdentifierToken> moduleNodeList = AbstractNodeFactory
                .createSeparatedNodeList(moduleNameToken);

        return NodeFactory.createImportDeclarationNode(
                SyntaxTokenConstants.SYNTAX_TREE_KEYWORD_IMPORT,
                importOrgNameNode,
                moduleNodeList,
                prefix,
                SYNTAX_TREE_SEMICOLON);
    }

    private static MinutiaeList createCommentMinutiaeList(String comment) {
        return NodeFactory.createMinutiaeList(
                AbstractNodeFactory.createCommentMinutiae(AUTOGENERATED_FILE_COMMENT),
                AbstractNodeFactory.createEndOfLineMinutiae(System.lineSeparator()),
                AbstractNodeFactory.createEndOfLineMinutiae(System.lineSeparator()),
                AbstractNodeFactory.createCommentMinutiae(comment),
                AbstractNodeFactory.createEndOfLineMinutiae(System.lineSeparator()),
                AbstractNodeFactory.createCommentMinutiae(COMMENT_SHOULD_NOT_BE_MODIFIED),
                AbstractNodeFactory.createEndOfLineMinutiae(System.lineSeparator()),
                AbstractNodeFactory.createEndOfLineMinutiae(System.lineSeparator()));
    }

    private static ImportDeclarationNode getImportDeclarationNodeWithAutogeneratedComment(
            String orgName, String moduleName, MinutiaeList commentMinutiaeList, ImportPrefixNode prefix) {
        Token orgNameToken = AbstractNodeFactory.createIdentifierToken(orgName);
        ImportOrgNameNode importOrgNameNode = NodeFactory.createImportOrgNameNode(
                orgNameToken,
                SyntaxTokenConstants.SYNTAX_TREE_SLASH);
        Token moduleNameToken = AbstractNodeFactory.createIdentifierToken(moduleName);
        SeparatedNodeList<IdentifierToken> moduleNodeList = AbstractNodeFactory
                .createSeparatedNodeList(moduleNameToken);
        Token importToken = NodeFactory.createToken(SyntaxKind.IMPORT_KEYWORD,
                commentMinutiaeList, NodeFactory.createMinutiaeList(AbstractNodeFactory
                        .createWhitespaceMinutiae(SPACE)));
        return NodeFactory.createImportDeclarationNode(
                importToken,
                importOrgNameNode,
                moduleNodeList,
                prefix,
                SYNTAX_TREE_SEMICOLON);
    }

    public static SyntaxTree generateTypeSyntaxTree(Module entityModule) {
        NodeList<ImportDeclarationNode> imports = AbstractNodeFactory.createEmptyNodeList();
        NodeList<ModuleMemberDeclarationNode> moduleMembers = AbstractNodeFactory.createEmptyNodeList();
        MinutiaeList commentMinutiaeList = createCommentMinutiaeList(String.format(
                AUTO_GENERATED_COMMENT_WITH_REASON, entityModule.getModuleName()));

        for (String modulePrefix : entityModule.getImportModulePrefixes()) {
            if (imports.isEmpty()) {
                imports = imports.add(getImportDeclarationNodeWithAutogeneratedComment(
                        KEYWORD_BALLERINA, modulePrefix,
                        commentMinutiaeList, null));
            } else {
                imports.add(getImportDeclarationNode(KEYWORD_BALLERINA, modulePrefix, null));
            }
        }
        boolean includeAutoGeneratedComment = imports.isEmpty();
        for (Entity entity : entityModule.getEntityMap().values()) {
            boolean hasRelations = false;
            for (EntityField field : entity.getFields()) {
                if (field.getRelation() != null) {
                    hasRelations = true;
                    break;
                }
            }
            if (includeAutoGeneratedComment) {
                moduleMembers = moduleMembers.add(createEntityRecord(entity, includeAutoGeneratedComment,
                        entityModule.getModuleName()));
                includeAutoGeneratedComment = false;
            } else {
                moduleMembers = moduleMembers.add(createEntityRecord(entity, includeAutoGeneratedComment,
                        entityModule.getModuleName()));
            }
            moduleMembers = moduleMembers.add(createEntityRecordOptionalized(entity));
            if (hasRelations) {
                moduleMembers = moduleMembers.add(createEntityRecordWithRelation(entity));
            }
            moduleMembers = moduleMembers.add(createEntityTargetType(entity, hasRelations));
            moduleMembers = moduleMembers.add(NodeParser.parseModuleMemberDeclaration(
                    String.format("public type %sInsert %s;", entity.getEntityName(),
                            entity.getEntityName())));
            moduleMembers = moduleMembers.add(createUpdateRecord(entity));
        }
        Token eofToken = AbstractNodeFactory.createIdentifierToken(EMPTY_STRING);
        ModulePartNode modulePartNode = NodeFactory.createModulePartNode(imports, moduleMembers, eofToken);
        TextDocument textDocument = TextDocuments.from(EMPTY_STRING);
        SyntaxTree balTree = SyntaxTree.from(textDocument);

        return balTree.modifyWith(modulePartNode);
    }

    private static ModuleMemberDeclarationNode createEntityRecord(Entity entity, boolean includeAutogeneratedComment,
            String moduleName) {
        StringBuilder recordFields = new StringBuilder();
        for (EntityField field : entity.getFields()) {
            if (entity.getKeys().stream().anyMatch(key -> key == field)) {
                recordFields.append(KEYWORD_READONLY);
                recordFields.append(SPACE);
                recordFields.append(field.getFieldType());
                if (field.isArrayType()) {
                    recordFields.append(ARRAY);
                }
                recordFields.append(SPACE);
                recordFields.append(field.getFieldName());
                recordFields.append(SEMICOLON);
                recordFields.append(SPACE);
            } else if (field.getRelation() != null) {
                if (field.getRelation().isOwner()) {
                    for (Relation.Key key : field.getRelation().getKeyColumns()) {
                        recordFields.append(key.getType());
                        recordFields.append(SPACE);
                        recordFields.append(key.getField());
                        recordFields.append(SEMICOLON);
                        recordFields.append(SPACE);
                    }
                }
            } else {
                recordFields.append(field.isOptionalType() ? field.getFieldType() + (field.isArrayType() ? ARRAY : "")
                        + QUESTION_MARK : field.getFieldType() + (field.isArrayType() ? ARRAY : ""));
                recordFields.append(SPACE);
                recordFields.append(field.getFieldName());
                recordFields.append(SEMICOLON);
                recordFields.append(SPACE);
            }

        }
        if (includeAutogeneratedComment) {
            StringBuilder commentBuilder = new StringBuilder();
            commentBuilder.append(AUTOGENERATED_FILE_COMMENT);
            commentBuilder.append("\n\n");
            commentBuilder.append(String.format(AUTO_GENERATED_COMMENT_WITH_REASON, moduleName));
            commentBuilder.append("\n");
            commentBuilder.append(COMMENT_SHOULD_NOT_BE_MODIFIED);
            commentBuilder.append("\n\n");
            commentBuilder.append("public type %s record {| %s |};");
            return NodeParser.parseModuleMemberDeclaration(String.format(commentBuilder.toString(),
                    entity.getEntityName().trim(), recordFields));
        }
        return NodeParser.parseModuleMemberDeclaration(String.format("public type %s record {| %s |};",
                entity.getEntityName().trim(), recordFields));
    }


    private static ModuleMemberDeclarationNode createEntityRecordOptionalized(Entity entity) {
        StringBuilder recordFields = new StringBuilder();
        for (EntityField field : entity.getFields()) {
            if (field.getRelation() != null) {
                if (field.getRelation().isOwner()) {
                    for (Relation.Key key : field.getRelation().getKeyColumns()) {
                        recordFields.append(key.getType());
                        recordFields.append(SPACE);
                        recordFields.append(key.getField());
                        recordFields.append(QUESTION_MARK);
                        recordFields.append(SEMICOLON);
                        recordFields.append(SPACE);
                    }
                }
            } else {
                recordFields.append(field.isOptionalType() ? field.getFieldType() + (field.isArrayType() ? ARRAY : "")
                        + QUESTION_MARK : field.getFieldType() + (field.isArrayType() ? ARRAY : ""));
                recordFields.append(SPACE);
                recordFields.append(field.getFieldName());
                recordFields.append(QUESTION_MARK);
                recordFields.append(SEMICOLON);
                recordFields.append(SPACE);
            }

        }
        return NodeParser.parseModuleMemberDeclaration(String.format("public type %sOptionalized record {| %s |};",
                entity.getEntityName().trim(), recordFields));
    }

    private static ModuleMemberDeclarationNode createEntityRecordWithRelation(Entity entity) {
        StringBuilder recordFields = new StringBuilder();
        recordFields.append(String.format("*%sOptionalized;", entity.getEntityName()));
        for (EntityField field : entity.getFields()) {
            if (field.getRelation() != null) {
                recordFields.append(String.format("%sOptionalized", field.getFieldType()));
                if (field.isArrayType()) {
                    recordFields.append("[]");
                }
                recordFields.append(SPACE);
                recordFields.append(field.getFieldName());
                recordFields.append(QUESTION_MARK);
                recordFields.append(SEMICOLON);
                recordFields.append(SPACE);
            }

        }
        return NodeParser.parseModuleMemberDeclaration(String.format("public type %sWithRelations record {| %s |};",
                entity.getEntityName().trim(), recordFields));
    }


    private static ModuleMemberDeclarationNode createEntityTargetType(Entity entity, boolean hasRelations) {
        return NodeParser.parseModuleMemberDeclaration(String.format("public type %sTargetType " +
                        "typedesc<%s>;",
                entity.getEntityName().trim(), entity.getEntityName().trim() +
                        (hasRelations ? "WithRelations" : "Optionalized")));
    }

    private static ModuleMemberDeclarationNode createUpdateRecord(Entity entity) {
        StringBuilder recordFields = new StringBuilder();
        for (EntityField field : entity.getFields()) {
            if (entity.getKeys().stream().noneMatch(key -> key == field)) {
                if (field.getRelation() != null) {
                    if (field.getRelation().isOwner()) {
                        for (Relation.Key key : field.getRelation().getKeyColumns()) {
                            recordFields.append(key.getType());
                            recordFields.append(" ");
                            recordFields.append(key.getField());
                            recordFields.append(QUESTION_MARK);
                            recordFields.append(SEMICOLON);
                            recordFields.append(SPACE);
                        }
                    }
                } else {
                    recordFields.append(field.isOptionalType()
                            ? field.getFieldType() + (field.isArrayType() ? ARRAY : "") + QUESTION_MARK
                            : field.getFieldType() + (field.isArrayType() ? ARRAY : ""));
                    recordFields.append(SPACE);
                    recordFields.append(field.getFieldName());
                    recordFields.append(QUESTION_MARK);
                    recordFields.append(SEMICOLON);
                    recordFields.append(SPACE);
                }
            }

        }
        return NodeParser.parseModuleMemberDeclaration(String.format("public type %sUpdate record {| %s |};",
                entity.getEntityName().trim(), recordFields));
    }

    private static String getEntityNameConstant(String entityName) {
        StringBuilder outputString = new StringBuilder();
        String[] splitedStrings = stripEscapeCharacter(entityName).split(REGEX_FOR_SPLIT_BY_CAPITOL_LETTER);
        for (String splitedString : splitedStrings) {
            if (outputString.length() != 0) {
                outputString.append(UNDERSCORE);
            }
            outputString.append(splitedString.toUpperCase(Locale.ENGLISH));
        }
        if (entityName.startsWith(SINGLE_QUOTE)) {
            return SINGLE_QUOTE + outputString;
        }
        return outputString.toString();
    }

    private static String stripEscapeCharacter(String fieldName) {
        return fieldName.startsWith(SINGLE_QUOTE) ? fieldName.substring(1) : fieldName;
    }
}
