/*
 *  Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 *  WSO2 Inc. licenses this file to you under the Apache License,
 *  Version 2.0 (the "License"); you may not use this file except
 *  in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package io.ballerina.persist.objects;
/**
 * Client Entity fieldMetaData class.
 *
 * @since 0.1.0
 *
 * @since 0.1.0
 */

public class FieldMetaData {
    private final String fieldName;
    private String fieldType;
    private String startValueOfAutoIncrement = "";
    private String stringLength = "191";
    private boolean autoGenerated = false;
    private Relation.RelationType relationType = Relation.RelationType.NONE;

    public FieldMetaData(String fieldName, String fieldType) {
        this.fieldName = fieldName;
        this.fieldType = fieldType;
    }

    public String getFieldName() {
        return fieldName;
    }

    public String getFieldType() {
        return fieldType;
    }

    public String getStartValueOfAutoIncrement() {
        return this.startValueOfAutoIncrement;
    }
    public String getStringLength() {
        return this.stringLength;
    }

    public boolean isAutoGenerated() {
        return this.autoGenerated;
    }

    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }
    public void setIsRelationType(Relation.RelationType relationType) {
        this.relationType = relationType;
    }
    public void setIsAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public void setStartValueOfAutoIncrement(String startValueOfAutoIncrement) {
        this.startValueOfAutoIncrement = startValueOfAutoIncrement;
    }

    public void setStringLength(String length) {
        this.stringLength = length;
    }

    public Relation.RelationType getRelationType() {
        return relationType;
    }

}
